#!/usr/bin/env python3

from parts import catalog
from prototypes import (Test, PinType)

for name, part in catalog.items():
    print(f"Checking: {name}")
    assert part.pincount
    assert part.name
    assert part.desc
    assert part.tests

    if len(part.pins) != part.pincount:
        raise RuntimeError(f"Number of pins doesn't match pin count")

    for p in part.pins:
        if p < 1 or p > part.pincount:
            raise RuntimeError(f"Wrong pin index: {p}")

    pin_roles = [p.role for p in part.pins.values()]
    if PinType.VCC not in pin_roles or PinType.GND not in pin_roles:
        raise RuntimeError("VCC or GND pin missing")

    test_names = [t.name for t in part.tests]
    if len(test_names) != len(set(test_names)):
        raise RuntimeError("Duplicate test names")

    for test in part.tests:
        assert test.name
        assert test.type in [Test.LOGIC, Test.DRAM, Test.UNIVIB]
        assert test.inputs
        assert test.outputs
        assert len(test.params) == Test.MAX_TEST_PARAMS
        for param in test.params:
            assert param in range(0, 256)

        for v in test.body:
            assert len(test.inputs) == len(v[0])
            assert v[1] is None or len(test.outputs) == len(v[1])

